### ISSUE TITLE
hey i tried to start Valkyrie in my server but i got this error

### ISSUE THREAD

**Issue by a-t-e-k-t-e-d** [NotSomething0/Valkyrie#12]
[    c-scripting-core] Creating script environments for Valkyrie
[     script:Valkyrie] Error loading script server/sv_filter.lua in resource Valkyrie: citizen:/scripting/lua/scheduler.lua:867: No such export registerMessageHook in resource chat
[     script:Valkyrie] stack traceback:
[     script:Valkyrie]  [C]: in function 'error'
[     script:Valkyrie]  citizen:/scripting/lua/scheduler.lua:867: in metamethod 'index'
[     script:Valkyrie]  @Valkyrie/server/sv_filter.lua:19: in main chunk
[    c-scripting-core] Failed to load script server/sv_filter.lua.
[ citizen-server-impl] Started resource Valkyrie

**Comment by NotSomething0** [comment]
You need to update the chat resource from the [cfx-server-data](https://github.com/citizenfx/cfx-server-data) repo this is noted in the instillation on the README

**Comment by a-t-e-k-t-e-d** [comment]
ok thk i fix but now i get this error 
[     script:Valkyrie] SCRIPT ERROR: @Valkyrie/server/sv_banmanager.lua:135: attempt to index a nil value (global 'logger')
[     script:Valkyrie] > handler (@Valkyrie/server/sv_banmanager.lua:135)

ps : did u have discord server ?

**Comment by NotSomething0** [comment]
The code in the main branch the one you most likely downloaded/cloned is considered unstable, download the resource from the release section for a stable build. I have a new release candidate planned for early next week so most new features will be implemented in that release. But you can just remove the logger call at the line specified that's old left over code and no I don't have a discord server

**Comment by a-t-e-k-t-e-d** [comment]
oh okay thk dude but i think u need to do discord server for help and not a complex server just channel to talk
