### ISSUE TITLE
COMPADRE

### ISSUE THREAD

**Issue by nutria22** [NotSomething0/Valkyrie#13]
**AGREGAME AL DISCORD QUE TE QUIERO DECIR UNA COSA**
Alexita#1234 

PLLIS

**Comment by NotSomething0** [comment]
You can ask your question here, I don't usually add random people on Discord. If you do decide to ask your question here please use English https://www.deepl.com/translator might be more helpful compared to google translate.

**Comment by nutria22** [comment]
A sorry I thought you spoke Spanish because in your Github bio it says Mexico and they speak Spanish there.
I wanted to see if I could help you with your project.

**Comment by NotSomething0** [comment]
I can see how that be confusing, but no I don't actually reside in Mexico and moreover don't speak Spanish lol. You're more than welcome to contribute, just open a pull request or make a feature request/bug report by opening an issue.

**Comment by nutria22** [comment]
Perfect
