### ISSUE TITLE
error: missing export "registerMessageHook"

### ISSUE THREAD

**Issue by soymaxi** [NotSomething0/Valkyrie#16]
![image](https://user-images.githubusercontent.com/63165345/210945475-faccfbc7-95fa-405a-a364-efe41242987e.png)

**Comment by NotSomething0** [comment]
It looks like you're using a custom chat resource or haven't updated your server-data resources in a while doing so should fix the issue. Valkyrie relies on the "registerMessageHook" export provided but the chat resource which seems to be missing from your version.
