### ISSUE TITLE
attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by Nanorithm** [NotSomething0/Valkyrie#18]
Getting this error when starting Valkyrie:

```
[     script:Valkyrie] SCRIPT ERROR: @Valkyrie/server/sv_main.lua:52: attempt to index a nil value (field '?')
[     script:Valkyrie] > fn (@Valkyrie/server/sv_main.lua:52)
```
![image](https://user-images.githubusercontent.com/13856563/226763925-711bb128-7510-4a07-bfc4-5ea4a7178b90.png)

I also noticed that when Valkyrie is enabled, sometimes I'm getting a red flashing on the minimap as if I was taking damage but I'm not sure how to exactly reproduce currently. Currently I can only see it happening while in a vehicle since I don't have minimap enabled otherwise.

![image](https://user-images.githubusercontent.com/13856563/226764418-1a125b31-b2e0-455b-8e44-c2f441ecb535.png)

It seems that if I restart Valkyrie while I am in the server, I don't get this issue but if I leave and rejoin it comes back which leads me to believe it may be something with an OnPlayerLoaded event maybe?

Currently using QBCore and version 1.5.0 from the release section but I updated the config and permissions cfgs and their respective exec's to match the master branch.

**Comment by NotSomething0** [comment]
You need to change `tracker[netId]` to `tracker[source]`, this is an oversight in the release. It's caused by the 'tracker' table attempting to access something that doesn't exist.
