### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by Molina1192** [NotSomething0/Valkyrie#19]
1. We need to figure out weather we want to use ox_core and ND for the server framework. (I would prefer to use ND for the time being as we already have the framework and the old server files which are tied to it)
2. **We need to make a database for the framework**.
3. Continue working on vehicles. (Will task Ryker and John with finding more vanilla CIV vehicles)
4. Make jobs so people can actually do legitimate CIV work to earn money.
5. Make a sales system for vehicles and make a general vehicle and set amount of money that everyone gets when they join the server for the first time.
6. Set blacklist for vehicles and weapons like we had with old server.
7. Release server when we feel it is ready for an initial test run.

**Comment by NotSomething0** [comment]
Linked to incorrect repository
