### ISSUE TITLE
Problem in config.blacklistweapon and other..

### ISSUE THREAD

**Issue by ariantryhard** [NotSomething0/Valkyrie#2]
Hello dear thanks for this anticheat its very good but there is 2 problem one is how can i set a player as admin?when i goto my server i ban from my server yes godmode and some one can be fix with add_ace identifier... but some functions for example blacklist events are do in all players admins and players and all them when they trigger event ban and 2 isuss is configs donesnt work for me when i spawn a blacklisted car or weapon no result i give and in my f8 and server console there is no erorr

**Comment by NotSomething0** [comment]
Hello, you can set a player as admin by doing add_principal identifier.YOURIDENTIFIERHERE group.admin in your server configuration file. Users with elevated permissions (admins) might get banned by accident do to permissions not getting updated fast enough, a solutioln for this issue will be pushed in a few days along with a better ban system so look out for that. Then if you could please post an image of the errors you're receiving It would be a lot easier to help you.
Thanks

**Comment by NotSomething0** [comment]
@ariantryhard I'm assuming all your issue have been resolved? I'll be closing this issue in 24 hours unless a response is given.
