### ISSUE TITLE
Script problem 

### ISSUE THREAD

**Issue by BigBober1** [NotSomething0/Valkyrie#21]
[     script:Valkyrie] SCRIPT ERROR: @Valkyrie/server/modules/sv_explosion.lua:174: attempt to index a nil value (global 'ProhibitedWeapons')
[     script:Valkyrie] > handler (@Valkyrie/server/modules/sv_explosion.lua:174)
[     script:Valkyrie] SCRIPT ERROR: @Valkyrie/server/modules/sv_events.lua:259: attempt to call a table value (global 'VPlayer')
[     script:Valkyrie] > handler (@Valkyrie/server/modules/sv_events.lua:259)

**Comment by NotSomething0** [comment]
You downloaded the main branch, which has breaking changes in it see [disclaimer](https://github.com/NotSomething0/Valkyrie?tab=readme-ov-file#disclaimer). The [releases](https://github.com/NotSomething0/Valkyrie/releases) section has ready-to-use code; please download it from there.
