### ISSUE TITLE
SCRIPT ERROR: @Valkyrie/server/sv_main.lua:60: No such export handlePlayer in resource Valkyrie

### ISSUE THREAD

**Issue by Nanorithm** [NotSomething0/Valkyrie#22]
I looked and I can't seem to find a definition for this either, line 60 is calling the handlePlayer export but I don't see a handlePlayer function anywhere.

`exports.Valkyrie:handlePlayer(netId, 'Maxium strikes', 'Exceeded maximum tracker strikes', true)`

**Comment by NotSomething0** [comment]
That's an oversight on my part; it seems I mistakenly created a release without pushing code from my local branch. The strike system has not been implemented in the v1.5.0 release, so you'll need to wait for v2. Alternatively, you can clone the code directly, which does have the strike system partially implemented. Although I just picked up this project again, so if you can wait for v2, I would do so.
