### ISSUE TITLE
[     script:Valkyrie] SCRIPT ERROR: @Valkyrie/server/sv_main.lua:92: attempt to index a nil value (global 'log')

### ISSUE THREAD

**Issue by CarlosA21** [NotSomething0/Valkyrie#23]
hi, im getting this error message when first installing the anticheat on my server, also i don't know where to put the discord webhook for the configuration and the messages
ill leave a picture of all the error messages that i have on the console of the server
![Captura de pantalla 2024-06-11 223249](https://github.com/NotSomething0/Valkyrie/assets/48720295/de3e9b79-8e0f-4181-be27-b725dc9398af)

![Captura de pantalla 2024-06-11 223347](https://github.com/NotSomething0/Valkyrie/assets/48720295/960042c7-83aa-4e6b-82a7-ffd79bfcddd2)

**Comment by NotSomething0** [comment]
Did you select "Download ZIP" when clicking on the green code icon? The main branch isn't in a working state if you did you can grab the latest release from the [releases](https://github.com/NotSomething0/Valkyrie/releases/latest) section and try using that instead.

**Comment by NotSomething0** [comment]
If this issue still occurs with the main branch feel free to reopen.
