### ISSUE TITLE
How do i unban people

### ISSUE THREAD

**Issue by ilikebanas** [NotSomething0/Valkyrie#3]
How do i unban people theres no sql or ban txt file?

**Comment by NotSomething0** [comment]
type `vunban <bandid>` in the console if you're using an older version which doesn't use banid's then type `vunban <license>` in the console these can also be used in game if need be.

**Comment by NotSomething0** [comment]
And you're correct there is no sql or ban txt file it uses FXServer built in kvp database to avoid unnecessary dependencies. If you for whatever reason need to wipe the ban list you can delete the folder titled 'db' in your root directory though this might cause issues as other resources you use could be using the same db.
