### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by TarikSogukpinar** [NotSomething0/Valkyrie#7]
Hello my friend, thanks for this beautiful system, but I am getting such errors, what is the reason? I am using qb-core.

@Valkyrie/server/sv.entities.lua:36: unexpected symbal near ')'
@Valkyrie/server/sv.entities.lua:250 attemp to index a nil value (global 'logger')
@Valkyrie/server/sv.filter.lua:57: ')' expected near '0'

Thank you !
![Screenshot_2](https://user-images.githubusercontent.com/70908075/156847455-7059fb21-76ed-463d-8f7f-4605bb3ab089.png)

**Comment by NotSomething0** [comment]
Sorry for the late reply been busy with life, you're downloading the master branch which is currently in a development state. Download the resource from the release section instead.
