### ISSUE TITLE
[SUGGESTION] Make UUID's actually unique

### ISSUE THREAD

**Issue by Ruqen** [NotSomething0/Valkyrie#9]
As seen on https://gist.github.com/jrus/3197011, using math.randomseed to seed math.random actually unique numbers is a pretty good idea and overall will improve math.random's quality.

Quote from [shmoli-itrs](https://gist.github.com/shmoli-itrs):

"Need to seed math.random to avoid generating the same uuid in subsequent runs"

This can be done by adding only 1 line in sv_banmanager.lua's UUID function:

`math.randomseed(os.time())`

If approved, I'll make and pull request these changes.

**Comment by NotSomething0** [comment]
Oops forgot to add lua54 'yes' to the manifest, this should be fixed now. Note Lua 5.4 added a new implementation for math.random which doesn't require a seed for uniqueness. Thanks for bringing this up though! [7a65092](https://github.com/NotSomething0/Valkyrie/commit/7a65092e26c027afd078c8de02f312b34e4c4033)
